name: racunko
description: 'Simple invoice making app.'
publish_to: 'none'
version: 1.4.0+140

environment:
  sdk: 3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  calendar_date_picker2: 2.0.1
  cloud_firestore: 6.1.0
  firebase_auth: 6.1.2
  firebase_core: 4.2.1
  flutter_displaymode: 0.7.0
  flutter_spinkit: 5.2.2
  flutter_swipe_action_cell: 3.1.6
  get_it: 9.0.5
  hive_ce: 2.15.1
  hive_ce_flutter: 2.3.3
  intl: 0.20.2
  logger: 2.6.2
  open_file: 3.5.10
  path_provider: 2.1.5
  pdf: 3.11.3
  uuid: 4.5.2
  watch_it: 2.1.1
  web: 1.1.1

dev_dependencies:
  build_runner: 2.10.3
  flutter_launcher_icons: 0.14.4
  flutter_native_splash: 2.4.7
  hive_ce_generator: 1.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/audio/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Thin.ttf
          weight: 100
        - asset: assets/fonts/Outfit-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Outfit-Light.ttf
          weight: 300
        - asset: assets/fonts/Outfit-Regular.ttf
          weight: 400
        - asset: assets/fonts/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Outfit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Outfit-Bold.ttf
          weight: 700
        - asset: assets/fonts/Outfit-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Outfit-Black.ttf
          weight: 900

# Run code generation - `dart run build_runner build -d`

# Configuration for 'flutter_launcher_icons'
# Run icon generation with 'dart run flutter_launcher_icons:main'
flutter_launcher_icons:
  image_path_android: 'assets/icon.png'
  image_path_ios: 'assets/icon.png'
  android: true
  ios: true
  adaptive_icon_background: 'assets/background.png'
  adaptive_icon_foreground: 'assets/splash_icon.png'
  adaptive_icon_foreground_inset: 16
  adaptive_icon_monochrome: 'assets/monochrome.png'
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: '#FFFFFF'
  web:
    generate: true
    image_path: 'assets/icon.png'
    background_color: '#FFFFFF'
    theme_color: '#FFFFFF'
  windows:
    generate: true
    image_path: 'assets/icon.png'
    icon_size: 48
  macos:
    generate: true
    image_path: 'assets/icon.png'

# Configuration for 'flutter_native_splash'
# Run splash screen generation with 'dart run flutter_native_splash:create'
flutter_native_splash:
  background_image: 'assets/splash.png'
  background_image_dark: 'assets/splash_dark.png'
  android_12:
    image: 'assets/splash_icon.png'
    image_dark: 'assets/monochrome.png'
    color: '#FFFFFF'
    color_dark: '#2B2D42'
